sudo: required
language: python

python:
  - "2.7"
  - "3.4"

addons:
  postgresql: "9.5"

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

before_script:
  - psql -c "CREATE DATABASE origami" -U postgres
  - psql -c "CREATE USER origamiuser WITH PASSWORD 'pass'" -U postgres
  - psql -c "ALTER ROLE origamiuser SET client_encoding TO 'utf8'" -U postgres
  - psql -c "ALTER ROLE origamiuser SET default_transaction_isolation TO 'read committed'" -U postgres
  - psql -c "ALTER ROLE origamiuser SET timezone TO 'UTC'" -U postgres
  - psql -c "ALTER USER origamiuser CREATEDB" -U postgres

env:
  - HOST=localhost PORT=8000 DB_NAME="origami" DB_USER="origamiuser" DB_PASS="password" DB_USER_EMAIL="test@test.com" DB_HOST="localhost" REDIS_HOST="redis"

before_install:
  - pip install -U pip
  - nvm install 6.0.0
  - nvm use 6.0.0
  - npm install -g yarn@0.23.4

install:
  - pip install -r requirements.txt
  - yarn install --ignore-engines

script:
  - npm run build
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test
  - coverage run --source='.' manage.py test api

cache:
  directories:
    - node_modules
    - $HOME/.cache/pip

after_success:
  - coveralls
